### ISSUE TITLE
Undefined symbol: firebase::ReferenceCountedFutureImpl::ReleaseMutexAndRunCallback(unsigned long)

### ISSUE THREAD

**Issue by faheemahmad1** [firebase/quickstart-cpp#43]
d: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/gamedepartment/Desktop/IOS Builds/JigsawTest5/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "firebase::ReferenceCountedFutureImpl::ReleaseMutexAndRunCallback(unsigned long)", referenced from:
      void firebase::ReferenceCountedFutureImpl::CompleteInternal<void, void firebase::ReferenceCountedFutureImpl::CompleteInternal<void>(unsigned long, int, char const*)::'lambda'(void*)>(unsigned long, int, char const*, void firebase::ReferenceCountedFutureImpl::CompleteInternal<void>(unsigned long, int, char const*)::'lambda'(void*) const&) in libStorage.a(storage_reference_ios_54a917f3a4ebcc04d14981a81202a365.o)
      void firebase::ReferenceCountedFutureImpl::CompleteInternal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void firebase::ReferenceCountedFutureImpl::CompleteWithResultInternal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(unsigned long, int, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)>(unsigned long, int, char const*, void firebase::ReferenceCountedFutureImpl::CompleteWithResultInternal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(unsigned long, int, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const&) in libStorage.a(storage_reference_ios_54a917f3a4ebcc04d14981a81202a365.o)
      void firebase::ReferenceCountedFutureImpl::CompleteInternal<void, void firebase::ReferenceCountedFutureImpl::CompleteInternal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(unsigned long, int, char const*)::'lambda'(void*)>(unsigned long, int, char const*, void firebase::ReferenceCountedFutureImpl::CompleteInternal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(unsigned long, int, char const*)::'lambda'(void*) const&) in libStorage.a(storage_reference_ios_54a917f3a4ebcc04d14981a81202a365.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![Screenshot 2020-01-17 at 10 15 02 AM](https://user-images.githubusercontent.com/59993501/72591578-540c8780-3922-11ea-8636-fc69b992fad1.png)

**Comment by jonsimantov** [comment]
As the friendly bot suggests, please update your post to follow the issue template, but in the meantime, did you include both the firebase.framework and firebase_storage.framework in your iOS project? Have you been able to get the Firebase Storage C++ quickstart to work on its own?

**Comment by faheemahmad1** [comment]
Cleared by Updating Firebase Libraries from Unity
